### ISSUE TITLE
`col.id` not used with `NMcheckData()`

### ISSUE THREAD

**Issue by billdenney** [philipdelff/NMdata#30] opened 2022-05-17 14:36 UTC
As you can tell, I'm using NMdata on some real projects now.  So, I'm having lots of good thoughts about it!  :)

I often use nonstandard names for NONMEM column names because I prefer keeping them closer to the SDTM and ADaM-like names in source data.  With that, I found that the `col.id` argument does not appear to be used with `NMcheckData()` based on the fact that it says the ID column is not found (when I think it should not be expected):

``` r
library(NMdata)
#> Warning: package 'NMdata' was built under R version 4.1.3
#> Welcome to NMdata. Best place to browse NMdata documentation is
#> https://philipdelff.github.io/NMdata/
library(tidyverse)
#> Warning: package 'ggplot2' was built under R version 4.1.3
#> Warning: package 'tibble' was built under R version 4.1.3
#> Warning: package 'dplyr' was built under R version 4.1.3
dat <- readRDS(system.file("examples/data/xgxr2.rds", package="NMdata"))

dat2 <-
  dat %>%
  rename(
    USUBJIDN=ID
  )
NMcheckData(dat2, col.id="USUBJIDN")
#>  column              check  N Nid
#>    EVID Subject has no obs 19   0
#>      ID   Column not found  1   0
#>     MDV   Column not found  1   0
```

<sup>Created on 2022-05-17 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by philipdelff** [comment] 2022-05-18 01:01
Thanks! This is now fixed in the master branch. Let me know if the issue is not resolved.

**Closed by philipdelff** 2022-05-18 01:01 UTC
